services:
  postgre:
    image: postgres:13.13
    ports:
      - 5433:5433
    networks:
      - miniblog_net
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: miniblog
      POSTGRES_DB: miniblog

  miniblog:
    image: walvesribeiro/miniblog:v3
    depends_on:
      - postgre
    build:
      context: ./src
      dockerfile: ./Dockerfile
    networks:
      - miniblog_net
    ports:
      - 8088:8088
    environment:
      DB_DATABASE: miniblog
      DB_USERNAME: miniblog
      DB_PASSWORD: pg1234
      DB_HOST: postgre

networks:
  miniblog_net:
    driver: bridge
