global:
  scrape_interval:     15s
  evaluation_interval: 30s  

scrape_configs: 
  - job_name: 'miniblog'    
    scrape_interval: 5s   
    static_configs:
      - targets: ['miniblog:8088']

  - job_name: 'prometheus'        
    static_configs:
      - targets: ['localhost:9090']
