apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.1
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_PASSWORD
              value: pg1234
            - name: POSTGRES_USER
              value: miniblog
            - name: POSTGRES_DB
              value: miniblog
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniblog
  template:
    metadata:
      labels:
        app: miniblog
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8088'
    spec:
      containers:
      - name: miniblog
        image: walvesribeiro/miniblog:latest
        ports:
        - containerPort: 8088
        env:
        - name: DB_DATABASE
          value: miniblog
        - name: DB_PASSWORD
          value: pg1234
        - name: DB_USERNAME
          value: miniblog
        - name: DB_HOST
          value: postgre
---
apiVersion: v1
kind: Service
metadata:
  name: miniblog
spec:
  selector:
    app: miniblog
  ports:
  - port: 80
    targetPort: 8088
  type: LoadBalancer
